import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Terms of Use</h1>
      <div className="space-y-6 text-gray-700 leading-relaxed">
        <p>Please check the details on this page carefully.</p>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">Preamble</h2>
          <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules framed thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
          <p className="mt-2">This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which requires publishing rules and regulations, privacy policy, and terms of use for access or usage of www.indexmoney.com.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">1. Parties and Definitions</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">1.1 Service Providers</h3>
          <p><strong>Index Money</strong><br />(Hereinafter collectively referred to as "IndexMoney.com," "We," "Us," "Our," which expression shall mean and include affiliates, successors, and permitted assigns)</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">1.2 User</h3>
          <p>"You," "Your," or "User" refers to any person accessing or using the Website.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">1.3 Website</h3>
          <p>www.indexmoney.com (referred to as the "Website") is owned and operated by Index Money.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">1.4 Member</h3>
          <p>"Member" refers to registered users who have created accounts on the Website.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">2. Acceptance of Terms</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">2.1 Binding Agreement</h3>
          <p>By accessing, browsing, or using this Website, you agree to be bound by these Terms of Use, along with:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Our Privacy Policy</li>
            <li>Our Disclaimer</li>
            <li>Any other policies incorporated by reference</li>
          </ul>
          <p>These collectively form a legally binding agreement between you and IndexMoney.com.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">2.2 Age and Capacity</h3>
          <p>By using this Website, you represent and warrant that:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>You are at least 18 years of age</li>
            <li>You are legally capable of entering into binding contracts</li>
            <li>You are not prohibited by law from using this Website</li>
            <li>All information you provide is accurate and complete</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">2.3 Conditional Use</h3>
          <p><strong>If you do not agree to these terms, do not use this website</strong></p>
          <p>Your continued use of the Website constitutes acceptance of these Terms and any modifications thereto.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">3. What We Do - Service Description</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">3.1 Nature of Services</h3>
          <p>IndexMoney.com provides an informational and connecting platform for unlisted shares wherein:</p>
          <h4 className="font-bold mt-2">For Investors (Buyers)</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Can register and create accounts</li>
            <li>Can search for unlisted shares of Pre-IPO companies</li>
            <li>Can view information about various companies</li>
            <li>Can express interest in buying shares via email</li>
            <li>Can conduct due diligence on investment opportunities</li>
          </ul>
          <h4 className="font-bold mt-2">For Shareholders (Sellers):</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Can register their interest in selling unlisted shares</li>
            <li>Can list shares they wish to liquidate</li>
            <li>Can connect with potential buyers</li>
          </ul>
          <h4 className="font-bold mt-2">Our Role</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>We provide information and facilitate connections</li>
            <li>We act as an intermediary for communication</li>
            <li>We do NOT execute transactions directly from our books</li>
            <li>We do NOT hold funds or securities</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">3.2 What We Are not</h3>
          <p>IndexMoney.com is not:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>A SEBI-registered stock broker or trading platform</li>
            <li>A recognized stock exchange</li>
            <li>An investment advisor</li>
            <li>A depository participant</li>
            <li>A custodian of securities or funds</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">3.3 Transaction Process</h3>
          <ol className="list-decimal pl-6 mb-2">
            <li>Member registers and creates an account</li>
            <li>Member searches for unlisted shares of interest</li>
            <li>Member conducts due diligence</li>
            <li>Member expresses interest via email/platform</li>
            <li>Index Money team attempts to find a counterparty (buyer/seller)</li>
            <li>If a match is found, both parties are connected via Index Money</li>
          </ol>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">4. User Registration and Account</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">4.1 Account Creation</h3>
          <p>To access certain features, you must register for an account by providing:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Accurate and complete information</li>
            <li>Valid contact details</li>
            <li>Proof of identity (as required)</li>
            <li>Financial information (as applicable)</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">4.2 Account Security</h3>
          <p>You are responsible for:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Maintaining confidentiality of your username and password</li>
            <li>All activities conducted under your account</li>
            <li>Notifying us immediately of unauthorized access</li>
            <li>Logging out after each session (especially on shared devices)</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">4.3 Account Accuracy</h3>
          <p>You agree to:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Provide truthful and accurate information</li>
            <li>Update information promptly when it changes</li>
            <li>Not impersonate any person or entity</li>
            <li>Not use offensive or inappropriate profile information</li>
            <li>Not create multiple accounts without permission</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">4.4 Account Termination by You</h3>
          <p>You may deactivate your account by:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Sending an email to support@indexmoney.com</li>
            <li>Following on-site account closure procedures</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">4.5 Account Termination by Us</h3>
          <p>We reserve the right to suspend or terminate your account if:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>You violate these Terms of Use</li>
            <li>You engage in fraudulent or illegal activities</li>
            <li>You provide false or misleading information</li>
            <li>Your account remains inactive for an extended period</li>
            <li>We are required to do so by law</li>
            <li>We decide to discontinue the service</li>
          </ul>
          <p><strong>Termination may be immediate and without prior notice.</strong></p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">5. User Obligations and Prohibited Conduct</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">5.1 Lawful Use</h3>
          <p>You agree to use the Website only for lawful purposes and in compliance with:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>All applicable Indian laws and regulations</li>
            <li>Securities laws and SEBI regulations</li>
            <li>Income Tax Act and tax laws</li>
            <li>Anti-money laundering laws</li>
            <li>FEMA regulations (for NRIs and foreign investors)</li>
            <li>These Terms of Use</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">5.2 Prohibited Activities</h3>
          <p>You shall not:</p>
          <h4 className="font-bold mt-2">Related to Trading and Investment:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Engage in market manipulation or price rigging</li>
            <li>Conduct insider trading or use material non-public information</li>
            <li>Create artificial demand or supply for shares</li>
            <li>Disseminate false or misleading information about companies</li>
            <li>Engage in fraudulent investment schemes</li>
            <li>Violate any securities laws or regulations</li>
          </ul>
          <h4 className="font-bold mt-2">Related to Website Use:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Use the Website for any illegal purpose</li>
            <li>Interfere with or disrupt the Website or servers</li>
            <li>Attempt to gain unauthorized access to accounts or systems</li>
            <li>Use automated systems (bots, scrapers) without authorization</li>
            <li>Introduce viruses, malware, or harmful code</li>
            <li>Reverse engineer or decompile any Website components</li>
            <li>Frame or mirror any part of the Website without permission</li>
          </ul>
          <h4 className="font-bold mt-2">Related to Content:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Post false, defamatory, or misleading content</li>
            <li>Infringe intellectual property rights of others</li>
            <li>Post obscene, offensive, or inappropriate content</li>
            <li>Spam or send unsolicited communications to other users</li>
            <li>Impersonate others or misrepresent affiliations</li>
          </ul>
          <h4 className="font-bold mt-2">Related to Conduct:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Harass, threaten, or abuse other users</li>
            <li>Engage in any form of discrimination</li>
            <li>Violate the privacy rights of others</li>
            <li>Collect information about other users without consent</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">5.3 Due Diligence Responsibility</h3>
          <p>You acknowledge and agree that:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>You are solely responsible for conducting due diligence</li>
            <li>You must independently verify all information</li>
            <li>You should consult professional advisors before investing</li>
            <li>Index Money provides information only and not advice</li>
            <li>Investment decisions are entirely your own</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">6. Intellectual Property Rights</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">6.1 Ownership</h3>
          <p>All content on this Website, including but not limited to:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Text, graphics, logos, images, and photographs</li>
            <li>Software, code, and technical elements</li>
            <li>Design, layout, and look-and-feel</li>
            <li>Trademarks, service marks, and trade names</li>
            <li>Data compilations and databases</li>
            <li>Articles, research reports, and analysis</li>
          </ul>
          <p>Is the exclusive property of IndexMoney.com or its licensors and is protected by applicable laws.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">6.2 Limited License</h3>
          <p>We grant you a limited, non-exclusive, non-transferable, revocable license to:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Access and use the Website for personal, non-commercial purposes</li>
            <li>View and download content for personal use only</li>
            <li>Print single copies of content for personal reference</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">6.3 Restrictions</h3>
          <p>You may NOT:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Reproduce, distribute, or republish Website content without written permission</li>
            <li>Modify, create derivative works, or adapt any content</li>
            <li>Use content for commercial purposes</li>
            <li>Remove or alter copyright notices or attributions</li>
            <li>Use our trademarks or branding without authorization</li>
            <li>Scrape, copy, or systematically extract data</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">6.4 User-Generated Content</h3>
          <p>If you submit, post, or upload any content to the Website:</p>
          <h4 className="font-bold mt-2">License Grant:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>You grant us a non-exclusive, worldwide, royalty-free, perpetual license</li>
            <li>To use, reproduce, modify, adapt, publish, and display such content</li>
            <li>For the purposes of operating and improving the Website</li>
          </ul>
          <h4 className="font-bold mt-2">Your Representations:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>You own or have rights to the content you submit</li>
            <li>Your content does not infringe third-party rights</li>
            <li>Your content complies with these Terms of Use</li>
            <li>You have obtained necessary consents and permissions</li>
          </ul>
          <h4 className="font-bold mt-2">Our Rights:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>We may remove any content at our sole discretion</li>
            <li>We may use your content for promotional purposes</li>
            <li>We are not responsible for user-generated content</li>
            <li>We do not endorse user-generated content</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">7. Information and Content Accuracy</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">7.1 No Guarantee of Accuracy</h3>
          <p>While we strive to provide accurate information:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Information may be outdated, incomplete, or incorrect</li>
            <li>Share prices and valuations are indicative and non-binding</li>
            <li>Company information may change without notice</li>
            <li>We rely on third-party sources that may be inaccurate</li>
            <li>We do not independently verify all information</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">7.2 No Obligation to Update</h3>
          <p>We are NOT obligated to:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Update information regularly</li>
            <li>Correct errors or inaccuracies</li>
            <li>Notify you of changes to company information</li>
            <li>Verify information provided by third parties</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">7.3 User Verification</h3>
          <p>You agree to:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Independently verify all information before relying on it</li>
            <li>Conduct your own research and due diligence</li>
            <li>Consult professional advisors</li>
            <li>Not hold us liable for inaccuracies or outdated information</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">8. Third-Party Links and Services</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">8.1 External Links</h3>
          <p>The Website may contain links to third-party websites, services, or resources. We do NOT:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Endorse or recommend third-party sites</li>
            <li>Control or monitor third-party content</li>
            <li>Assume responsibility for third-party practices</li>
            <li>Guarantee the accuracy of external content</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">8.2 Your Responsibility</h3>
          <p>When you access third-party links:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>You do so at your own risk</li>
            <li>You are subject to their terms and policies</li>
            <li>You should review their privacy policies</li>
            <li>We are not responsible for any consequences</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">9. Disclaimers and Limitation of Liability</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">9.1 "AS IS" Basis</h3>
          <p>The website and all content are provided on an "as is" and "as available" basis without any warranties of any kind. We disclaim all warranties, express or implied, including:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Warranties of merchantability</li>
            <li>Fitness for a particular purpose</li>
            <li>Non-infringement</li>
            <li>Accuracy or completeness</li>
            <li>Uninterrupted or error-free service</li>
            <li>Security or virus-free content</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">9.2 No Investment Advice</h3>
          <p>WE DO NOT PROVIDE:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Investment advice or recommendations</li>
            <li>Financial planning services</li>
            <li>Tax advice</li>
            <li>Legal advice</li>
            <li>Personalized guidance</li>
          </ul>
          <p>All information is for general informational purposes only.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">9.3 No Guarantee of Results</h3>
          <p>We make no guarantees regarding:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Returns on investments</li>
            <li>Success of IPOs or listings</li>
            <li>Availability of shares for purchase</li>
            <li>Completion of transactions</li>
            <li>Future performance of companies</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">9.4 Limitation of Liability</h3>
          <p>To the maximum extent permitted by law: Index Money, and its respective directors, officers, employees, agents, affiliates, and partners shall NOT be liable for any:</p>
          <h4 className="font-bold mt-2">Types of Damages:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Direct, indirect, incidental, or consequential damages</li>
            <li>Investment losses or financial damages</li>
            <li>Loss of profits, revenue, or business opportunities</li>
            <li>Loss of data or information</li>
            <li>Loss of goodwill or reputation</li>
            <li>Punitive or exemplary damages</li>
          </ul>
          <h4 className="font-bold mt-2">Causes:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Use or inability to use the Website</li>
            <li>Errors, omissions, or inaccuracies in content</li>
            <li>Unauthorized access to your information</li>
            <li>Service interruptions or technical failures</li>
            <li>Third-party actions or content</li>
            <li>Fraudulent transactions or schemes</li>
            <li>Reliance on Website information</li>
            <li>Investment decisions made based on Website content</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">9.5 Assumption of Risk</h3>
          <p>You expressly acknowledge and agree that:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>You use the Website entirely at your own risk</li>
            <li>You are solely responsible for investment decisions</li>
            <li>You understand the risks of unlisted share investments</li>
            <li>You will not hold us liable for any losses or damages</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">10. Indemnification</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">10.1 Your Agreement to Indemnify</h3>
          <p>You agree to indemnify, defend, and hold harmless IndexMoney.com and its respective directors, officers, employees, agents, affiliates, successors, and assigns from and against any and all:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Claims, demands, actions, or proceedings</li>
            <li>Losses, damages, liabilities, costs, and expenses</li>
            <li>Legal fees and dispute resolution costs</li>
          </ul>
          <p>Arising from or related to:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Your use or misuse of the Website</li>
            <li>Your violation of these Terms of Use</li>
            <li>Your violation of any applicable laws or regulations</li>
            <li>Your violation of third-party rights</li>
            <li>Your investment decisions or transactions</li>
            <li>Fraud, negligence, or willful misconduct on your part</li>
            <li>Content you submit or post on the Website</li>
            <li>Tax liabilities arising from your transactions</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">10.2 Defense and Settlement</h3>
          <ul className="list-disc pl-6 mb-2">
            <li>Assume exclusive defense and control of any matter subject to indemnification</li>
            <li>Require your cooperation in defending such claims</li>
            <li>Approve any settlement that affects our rights or obligations</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">11. Fees and Payments</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">11.1 Service Fees</h3>
          <ul className="list-disc pl-6 mb-2">
            <li>Premium membership or subscription</li>
            <li>Enhanced features or services</li>
            <li>Transaction facilitation fees</li>
            <li>Information access fees</li>
          </ul>
          <p>Fee details will be disclosed before you incur any charges.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">11.2 Payment Terms</h3>
          <ul className="list-disc pl-6 mb-2">
            <li>All fees are in Indian Rupees (INR) unless otherwise stated</li>
            <li>Fees are non-refundable unless explicitly stated</li>
            <li>You are responsible for all applicable taxes</li>
            <li>Payment must be made through approved methods</li>
            <li>We may change fees with prior notice</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">11.3 Taxes</h3>
          <ul className="list-disc pl-6 mb-2">
            <li>Income tax on capital gains from share sales</li>
            <li>GST or other applicable taxes on services</li>
            <li>All tax filings and compliance</li>
            <li>Consulting with tax advisors</li>
          </ul>
          <p>We are NOT responsible for your tax obligations.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">12. Privacy and Data Protection</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">12.1 Privacy Policy</h3>
          <p>Your use of the Website is also governed by our Privacy Policy.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">12.2 Consent to Data Use</h3>
          <p>By using the Website, you consent to our data practices as described in the Privacy Policy.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">12.3 Data Security</h3>
          <p>While we implement security measures:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>We cannot guarantee absolute security</li>
            <li>You are responsible for protecting your account credentials</li>
            <li>Report any security incidents immediately</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">13. Modifications to Terms</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">13.1 Right to Modify</h3>
          <p>We reserve the right to modify these Terms.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">13.2 Notification</h3>
          <ul className="list-disc pl-6 mb-2">
            <li>Email to your registered email address</li>
            <li>Prominent notice on the Website</li>
            <li>Pop-up notification upon login</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">13.3 Effective Date</h3>
          <p>Changes become effective immediately upon posting.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">13.4 Continued Use</h3>
          <p>Your continued use after modifications constitutes acceptance.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">14. Termination of Service</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">14.1 Our Right to Terminate</h3>
          <p>We may, at our sole discretion:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Suspend or terminate your access immediately</li>
            <li>Remove or disable content</li>
            <li>Modify or discontinue any part of the Website</li>
            <li>Refuse service to anyone</li>
          </ul>
          <p>Without:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Prior notice or warning</li>
            <li>Liability or obligation to you</li>
            <li>Providing reasons for termination</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">14.2 Effects of Termination</h3>
          <p>Upon termination:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Your right to use the Website immediately ceases</li>
            <li>We may delete your account and data</li>
            <li>You remain liable for obligations incurred before termination</li>
            <li>Provisions that should survive termination remain in effect</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">14.3 Survival</h3>
          <p>The following provisions survive termination:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Intellectual Property Rights</li>
            <li>Disclaimers and Limitation of Liability</li>
            <li>Indemnification</li>
            <li>Governing Law and Dispute Resolution</li>
            <li>Any other provisions that by their nature should survive</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">15. Governing Law and Jurisdiction</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">15.1 Governing Law</h3>
          <p>These Terms of Use shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">15.2 Exclusive Jurisdiction</h3>
          <p>Any disputes arising out of or relating to these terms or the website shall be subject to the exclusive jurisdiction of the courts in India.</p>
          <p>You irrevocably submit to the jurisdiction of such courts.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">15.3 Dispute Resolution Process</h3>
          <p>Step 1: Negotiation (15 days) Before initiating legal proceedings, parties agree to attempt good faith negotiations to resolve disputes.</p>
          <h4 className="font-bold mt-2">Negotiation begins:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li>Within 15 days of written dispute notice</li>
            <li>Through designated representatives</li>
            <li>In good faith with intent to resolve</li>
          </ul>
          <p><strong>Step 2:</strong> Arbitration (if negotiation fails) If negotiation fails, the dispute shall be referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996.</p>
          <h4 className="font-bold mt-2">Arbitration Terms:</h4>
          <ul className="list-disc pl-6 mb-2">
            <li><strong>Number of Arbitrators:</strong> One (1) sole arbitrator</li>
            <li><strong>Appointment:</strong> Jointly appointed by both parties within 30 days</li>
            <li><strong>Failure to Appoint:</strong> If parties fail to agree, arbitrator appointed in accordance with the Act</li>
            <li><strong>Seat of Arbitration:</strong> India</li>
            <li><strong>Language:</strong> English</li>
            <li><strong>Arbitration Rules:</strong> Arbitration and Conciliation Act, 1996</li>
            <li><strong>Award:</strong> Final and binding on both parties</li>
          </ul>
          <p><strong>During arbitration:</strong> Both parties shall continue to exercise remaining rights and fulfill remaining obligations under these Terms of Use</p>
          <p><strong>Step 3:</strong> Legal Proceedings Only after exhausting the above steps may either party initiate legal proceedings in the courts of India.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">15.4 Costs</h3>
          <p>Each party shall bear its own costs unless:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>The arbitrator or court determines otherwise</li>
            <li>The party acted frivolously or in bad faith</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">16. Miscellaneous Provisions</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">16.1 Entire Agreement</h3>
          <p>These Terms of Use, together with our Privacy Policy and Disclaimer, constitute the entire agreement between you and IndexMoney.com regarding use of the Website, superseding any prior agreements.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.2 Severability</h3>
          <p>If any provision of these Terms is found to be invalid, illegal, or unenforceable:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>That provision shall be limited or eliminated to the minimum extent necessary</li>
            <li>The remaining provisions shall remain in full force and effect</li>
            <li>The invalid provision shall be replaced with a valid provision that achieves the original intent</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.3 Waiver</h3>
          <p>Our failure to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision unless acknowledged in writing.</p>
          <p>No waiver shall be deemed a continuing waiver unless explicitly stated.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.4 Assignment</h3>
          <ul className="list-disc pl-6 mb-2">
            <li>You may not assign or transfer these Terms or your account without our written consent</li>
            <li>We may assign these Terms and transfer our rights and obligations to any third party without your consent</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.5 Force Majeure</h3>
          <p>We shall not be liable for any failure to perform due to circumstances beyond our reasonable control, including:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Acts of God (earthquakes, floods, storms)</li>
            <li>War, terrorism, or civil unrest</li>
            <li>Government actions or regulations</li>
            <li>Internet or telecommunications failures</li>
            <li>Strikes or labor disputes</li>
            <li>Pandemics or public health emergencies</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.6 Notices</h3>
          <p><strong>Notices to You:</strong> We may provide notices via:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Email to your registered email address</li>
            <li>Posting on the Website</li>
            <li>In-app notifications</li>
          </ul>
          <p><strong>Notices to Us:</strong> We may provide notices via:</p>
          <ul className="list-disc pl-6 mb-2">
            <li><strong>Email:</strong> support@indexmoney.com</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.7 Relationship</h3>
          <p>No agency, partnership, joint venture, employment, or franchise relationship is created between you and IndexMoney.com by these Terms or your use of the Website.</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.8 Headings</h3>
          <p>Section headings are for convenience only and shall not affect the interpretation of these Terms</p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">16.9 Language</h3>
          <p>These Terms are drafted in English. If translated to other languages, the English version shall prevail in case of any conflict.</p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">17. Regulatory Compliance</h2>
          <h3 className="text-lg font-bold text-gray-800 mb-2">17.1 Your Compliance Obligations</h3>
          <p><strong>Securities Laws:</strong></p>
          <ul className="list-disc pl-6 mb-2">
            <li>Securities Contract (Regulation) Act, 1956</li>
            <li>SEBI Act and SEBI regulations</li>
            <li>Companies Act, 2013</li>
            <li>Any other applicable securities laws</li>
          </ul>
          <p><strong>Tax Laws:</strong></p>
          <ul className="list-disc pl-6 mb-2">
            <li>Income Tax Act, 1961</li>
            <li>GST laws</li>
            <li>Tax filing and reporting obligations</li>
          </ul>
          <p><strong>Other Laws:</strong></p>
          <ul className="list-disc pl-6 mb-2">
            <li>Foreign Exchange Management Act (FEMA) for NRIs</li>
            <li>Prevention of Money Laundering Act (PMLA)</li>
            <li>Information Technology Act, 2000</li>
            <li>Any other applicable Indian laws</li>
          </ul>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">17.2 Know Your Customer (KYC)</h3>
          <p>We may require you to:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Complete KYC procedures</li>
            <li>Provide identity and address proof</li>
            <li>Submit PAN card and other documents</li>
            <li>Update KYC information periodically</li>
          </ul>
          <p><strong>Failure to complete KYC may result in account restrictions.</strong></p>
          <h3 className="text-lg font-bold text-gray-800 mt-4 mb-2">17.3 Reporting Obligations</h3>
          <p>You are responsible for:</p>
          <ul className="list-disc pl-6 mb-2">
            <li>Reporting capital gains to tax authorities</li>
            <li>Filing necessary tax returns</li>
            <li>Disclosing unlisted share holdings as required</li>
            <li>Complying with all reporting requirements</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold text-gray-900 mb-2">18. Contact Information</h2>
          <p>For questions, support, or concerns regarding these Terms of Use:</p>
          <h5 className="font-bold mt-2">General Inquiries:</h5>
          <ul className="list-disc pl-6 mb-2">
            <li><strong>Email: support@indexmoney.com</strong></li>
            <li><strong>Website: www.indexmoney.com</strong></li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export default TermsAndConditions;
